# only used for local development for ease

FROM ubuntu:20.04

LABEL maintainer="srihari.vishnu@gmail.com"
LABEL version="0.1"
LABEL description="This is the image for the dockbox docker engine server"

ARG DEBIAN_FRONTEND=noninteractive
ARG PORT

RUN apt update && apt upgrade -y && apt install -y socat

EXPOSE 2375

CMD socat TCP-LISTEN:2375,reuseaddr,fork unix:///var/run/docker.sock
