version: "3.9" # optional since v1.27.0
services:
  docker:
    build:
      context: .
      dockerfile: Dockerfile.docker
      args:
        - PORT=2375
    image: dockbox/docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    image: dockbox/server
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=development
      - PORT=8000
      - DOCKER_SERVER_HOST=docker:2375
